### ISSUE TITLE
It should not crash on style which works with maplibre 10.2.0

### ISSUE THREAD

**Issue by elican-doenyas** [maplibre/maplibre-native#3042] opened 2024-11-26 12:45 UTC
EDIT: The cause I thought in the initial description of the issue is incorrect. After further investigation we pinpointed the actual cause of the experienced crash which I added as a comment to the issue: https://github.com/maplibre/maplibre-native/issues/3042#issuecomment-2510799281

When I use a style.json with map libre version 11.5.1 which does not have;

"maputnik:renderer": "mbgljs"

in its metadata, the maplibre sdk causes a crash with the log attached.
[maplibre-renderer-crash.txt](https://github.com/user-attachments/files/17919481/maplibre-renderer-crash.txt)

1. Use a style.json that does not have the "maputnik:renderer": "mbgljs" in its metadata
2. Open a map using this style.json
3. Observe crash upon drawing certain tiles

Expected behavior:
The Maplibre SDK should not crash, or mention that this metadata is mandatory.

 - OS: Android - 14
 - Platform: Android
 - Version: 11.5.1
 - Device: Samsung S23

This issue does not happen on version maplibre 10.2.0. It only started happening after a switch to version 11.5.1.

**Comment by louwers** [comment] 2024-11-26 12:49
The demotiles style https://demotiles.maplibre.org/style.json does not have this property. And it works.

Could you provide the style.json that is causing the crash?

**Comment by elican-doenyas** [comment] 2024-12-04 08:52
@louwers Please let me know if there is any more information needed or if this is sufficient.

**Comment by louwers** [comment] 2024-12-04 11:54
@elican-doenyas I am not able to reproduce the issue with the style you provided.

**Comment by louwers** [comment] 2024-12-04 18:08
This will be fixed in the next Android release.

Thanks for the report @elican-doenyas!

**Closed** 2024-12-04 20:57 UTC
Labels: android, OpenGL
