### ISSUE TITLE
Incorrect rendering of lines using pattern images

### ISSUE THREAD

**Issue by georgbachmann** [maplibre/maplibre-native#2621] opened 2024-07-16 10:28 UTC
The problem seems to be a line that is drawn using a pattern image.
First of, here some images. First one is how it should look. You can see those cliff lines. I marked them with two red arrows. (There are a couple of them)
<img width="1117" alt="Bildschirmfoto 2024-07-16 um 11 50 33" src="https://github.com/user-attachments/assets/cc6c0699-5fa6-4bd2-a31f-6bc08f95c213">

And the exact same style using the latest (6.5.1) iOS version of MapLibre does not render them any more.
![IMG_6378D13C9EA6-1 (1)](https://github.com/user-attachments/assets/6ece3840-5143-4333-a93d-05861d5165bc)

The part inside the style is the following:
```
      {
          "id": "cliff",
          "type": "line",
          "source": "composite",
          "source-layer": "cliff",
          "filter": ["match", ["get", "type"], ["cliff"], true, false],
          "layout": {"line-cap": "square"},
          "paint": {
              "line-color": "hsl(0, 6%, 28%)",
              "line-opacity": [
                  "interpolate",
                  ["linear"],
                  ["zoom"],
                  12,
                  0,
                  15,
                  1,
                  22,
                  1
              ],
              "line-pattern": "cliff",
              "line-offset": 4,
              "line-width": 4
          }
      }
```

And I also attached the cliff.svg that we are using.
The old (pre-metal) version is properly rendering the style.

I don't really want to share my style url here, but if one of the developers who might look at this issue want to use it, please feel free to e.g. contact me on the slack channel -> I am `@Georg` there (same avatar image as here on github :-) )

**Platform information (please complete the following information):**
 - OS: iOS
 - Platform iOS
 - Version 6.5.1
 
![cliff](https://github.com/user-attachments/assets/d7a5764c-7347-412f-8dde-d3e3b16050f1)

**Comment by louwers** [comment] 2024-07-16 12:02
Could you try to see what MapLibre GL JS does with this?

Any chance you could simplify the example? Maybe see if you can reproduce it with a simple GeoJSON source? Or maybe extract data for one tile? Ideally we would create a (render) regression test out of this.

**Comment by georgbachmann** [comment] 2024-07-16 12:55
Thanks for your help!

I just tried a MapLibre GL sample (4.5.0) exchanged the style url and zoomed to my area and it was rendering correct.
I tried to create a super small sample style with ONLY that one layer and a geojson source but that seems to work?!?

Not sure how I can provide the proper failing example. Cause the screenshots that you see above are just a plain MLNMapView with my style-url.

**Comment by JesseCrocker** [comment] 2024-08-05 21:42
I am also seeing this same issue. 
The road in the center should be using all the same pattern, but that road is split at a tile boundary, with one side using the correct image, and one using the wrong image.

I am seeing other cases where the correct image is used, but as i zoom in it switches to the wrong image.

![Uploading Simulator Screenshot - iPhone 15 - 2024-08-05 at 15.40.01.png…]()

**Comment by sjg-wdw** [comment] 2024-09-17 16:40
@louwers is this a duplicate of another issue?  Seems like we might have a couple of texture reuse problems.

**Comment by louwers** [comment] 2024-09-17 17:23
Not that I am aware of.

**Comment by iwo** [comment] 2024-09-24 11:38
We are seeing the same issue in our app.
It's easiest to reproduce on Android but it's also happens on web if you fiddle enough with the zoom level.

We initially thought that it may be an issue with sprite caching but after clearing all the caches it's still reproducible.

**Comment by iwo** [comment] 2024-10-04 14:39
We are still observing this rendering problem and it's clearly related to the drawable renderer. On legacy renderer `line-pattern` works much better.

This issue may be a duplicate of https://github.com/maplibre/maplibre-native/issues/2735
In https://github.com/maplibre/maplibre-native/issues/2735 there is a simple demo to reproduce the pattern mixup.

Regarding my previous comment about web, we were able to eliminate the issue on web using a constant `line-pattern` string instead of expression but it didn't help on Android.

**Comment by JesseCrocker** [comment] 2024-10-30 16:05
#2735 was closed, does that mean this is also fixed?

**Comment by louwers** [comment] 2024-10-30 16:50
@JesseCrocker Could you check?

**Comment by georgbachmann** [comment] 2024-11-04 10:29
For me it seems that 6.8.0 does not have the problem any more. Awesome job and thank you very much!!!!!
So I could close that issue if you want?

**Closed** 2024-11-04 10:44 UTC
Labels: bug
