### ISSUE TITLE
Use of 'mgl_does:have:' as an NSExpression function is forbidden.

### ISSUE THREAD

**Issue by georgiosantoniadis** [maplibre/maplibre-native#1645] opened 2023-09-18 14:08 UTC
**Describe the bug**
I noticed a lot of error logs in the console:

`[general] NSPredicate: Use of 'mgl_does:have:' as an NSExpression function is forbidden.`

Apparently there already was a similar issue that has been fixed, but I still receive above console-log:
https://github.com/maplibre/maplibre-native/issues/331

What I try to solve is support indoor floor levels as described here:
https://github.com/maplibre/maplibre-native/issues/703

For this, I use the variable MGLVectorStyleLayer.predicate.mgl_jsonExpressionObject, and thats where the log comes from:
<img width="578" alt="image" src="https://github.com/maplibre/maplibre-native/assets/24453906/04ef56a6-e1ff-4de8-94a6-e3ca07ff1498">

**Expected behavior**
No runtime errors

**Platform information (please complete the following information):**
 - OS: 16.6.1
 - Platform: iPhone X
 - Version: MapLibre GL Native 5.13.0

Do you need further information?

**Comment by louwers** [comment] 2023-09-18 21:54
Thanks, I think the issue was prematurely declared 'fixed'.

@ianthetechie Did your looking into this result in any discoveries?

**Comment by ianthetechie** [comment] 2023-09-19 08:55
Yeah, I ran into what is likely the same root issue described in #331. This may have been fixed subsequently, but I couldn't find a way to get it working with v5.13, so I abandoned the search until I could get a build off `master` which has totally refactored this.

If I get some time I'll try building master to investigate but can't promise anything this week.

I've posted a fuller update in the other issue with other approaches I tried (+failed).

**Comment by alanchenboy** [comment] 2023-09-20 10:19
+ (instancetype)mgl_expressionForDoesExpression:(NSExpression *)operand have:(NSExpression*)key {
    if (@available(iOS 15.5, macOS 12, *)) {
        NSExpression *functionExpression = [NSExpression expressionWithFormat:@"sum({})"];
        return [NSExpression expressionForFunction:functionExpression.operand
                                      selectorName:@"mgl_does:have:"
                                         arguments:@[operand, key]];
    } else {
        return [NSExpression expressionForFunction:@"mgl_does:have:" arguments:@[operand, key]];
    }
}

**Comment by louwers** [comment] 2024-07-08 14:51
Duplicate of https://github.com/maplibre/maplibre-native/issues/1820

**Closed by louwers** 2024-07-08 14:51 UTC
Labels: bug, iOS
