### ISSUE TITLE
NSPredicate: Use of 'mgl_attributed:' as an NSExpression function is forbidden.

### ISSUE THREAD

**Issue by hactar** [maplibre/maplibre-native#3020] opened 2024-11-15 15:42 UTC
**Describe the bug**
When loading a MapStyle that contains

```
        "text-field": [
          "get",
          "name"
        ],
```

MapLibre iOS prints errors into the Xcode console, in the form of

```
NSPredicate: Use of 'mgl_attributed:' as an NSExpression function is forbidden.
NSPredicate: Use of 'mgl_coalesce:' as an NSExpression function is forbidden.
```

It appears though that the map style works perfectly fine even though these errors are thrown.

**To Reproduce**
1. Load a map style like the one below.
2. Look at the Xcode console.

**Expected behavior**
No error messages in console.

**Platform information (please complete the following information):**
 - OS: iOS 18
 - Platform: iOS
 - Version: 6.8.0, but this happened in previous versions already.

**Additional context**
Minimal map style where I see this happening. Probably needs an access token to load though, so if you need access to this map style to test, please message me.

```
{
  "version": 8,
  "name": "Bikemap 3D 2022",
  "metadata": {
    "maputnik:renderer": "mbgljs",
    "openmaptiles:version": "3.x"
  },
  "center": [
    16.3738,
    48.2082
  ],
  "zoom": 13,
  "bearing": 0,
  "pitch": 0,
  "sources": {
    "openmaptiles": {
      "type": "vector",
      "url": "https://dev-tiles.bikemap.net/data/austria-vector.json"
    },
    "terrain": {
      "type": "raster-dem",
      "url": "https://api.maptiler.com/tiles/terrain-rgb/tiles.json"
    }
  },
  "sprite": "https://dev-tiles.bikemap.net/styles/bikemap-2021-3D/sprite",
  "glyphs": "[https://dev-tiles.bikemap.net/fonts/{fontstack}/{range}.pbf](https://dev-tiles.bikemap.net/fonts/%7Bfontstack%7D/%7Brange%7D.pbf)",
  "layers": [
    {
      "id": "poi_restaurant",
      "type": "symbol",
      "source": "openmaptiles",
      "source-layer": "poi",
      "minzoom": 15,
      "maxzoom": 22,
      "layout": {
        "text-padding": 2,
        "text-anchor": "top",
        "icon-image": "osmpoi-restaurant-light",
        "text-field": [
          "get",
          "name"
        ],
        "text-offset": [
          0,
          0.6
        ],
        "text-size": 12,
        "text-max-width": 9,
        "symbol-avoid-edges": true,
        "visibility": "visible",
        "icon-padding": 2,
        "icon-anchor": "bottom",
        "icon-offset": [
          0,
          5
        ]
      },
      "paint": {
        "text-halo-blur": 0,
        "text-color": "#1F4258",
        "text-halo-width": 0.5,
        "text-halo-color": "rgba(255, 255, 255, 0.75)"
      }
    }
  ],
  "terrain": {
    "source": "terrain",
    "exaggeration": 1
  },
  "id": "xej9nmzhh",
  "owner": "Bikemap"
}
```

**Comment by louwers** [comment] 2024-11-15 18:01
Duplicate of https://github.com/maplibre/maplibre-native/issues/331

**Closed by louwers** 2024-11-15 18:01 UTC
Labels: bug, iOS
